# https://www.tweek.top/archives/1706060591396
# version: '3'
# services:
#   maccms10:
#       volumes:
#           - ./mnt/maccms:/data
#           - ./mnt/maccms/template:/opt/maccms10/template
#       ports:
#           - '7878:7878'
#       image: gs0245/maccms10
#         #network_mode: host (optional)
#       restart: always

version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest' #最新版npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  maccms10:
      volumes:
          - ./mnt/maccms:/data
          - ./mnt/maccms/template:/opt/maccms10/template
      ports:
          - '7878:7878'
      image: gs0245/maccms10
        #network_mode: host (optional)
      restart: always
