services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    environment:
      VERSION: "win7"
      RAM_SIZE: "1.5G"
      CPU_CORES: "2"
      DISK_SIZE: "12G"
      USERNAME: "dd"
      PASSWORD: "7654321234567"
      LANGUAGE: "Chinese"   
    volumes:
      - /home/winarmdisk:/storage
      - /home/winarmshare:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 5000:5000/tcp
    stop_grace_period: 2m