services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    environment:
      # VERSION: "https://example.com/win.iso"
      # VERSION: "win7"
      VERSION: "core11"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      DISK_SIZE: "15G"
      USERNAME: "qq"
      PASSWORD: "7654321234567"
      LANGUAGE: "Chinese"   
    volumes:
      # - /home/tiny11corex64beta1.iso:/custom.iso
      - /home:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 5090:5090/tcp
    stop_grace_period: 2m
    networks:
      - 1panel-v4v6

networks:
  1panel-v4v6:
    external: true