
echoT(){ FLAG=$1 && shift && echo -e "\033[39m$FLAG\033[39m$@";}
echoY(){ FLAG=$1 && shift && echo -e "\033[38;5;148m$FLAG\033[39m$@";}
echoG(){ FLAG=$1 && shift && echo -e "\033[38;5;71m$FLAG\033[39m$@"; }
echoB(){ FLAG=$1 && shift && echo -e "\033[38;1;34m$FLAG\033[39m$@" ;}
echoR(){ FLAG=$1 && shift && echo -e "\033[38;5;203m$FLAG\033[39m$@"; }

FCLS='\033[34m'        # 前景色：蓝色
FTCZ='\033[0m'         # 字体：重置所有
FTSS='\033[5m'         # 字体：闪烁

VLATEST="${FCLS}${FTSS}NEW${FTCZ}" # 蓝色闪烁字体
url_redir='https://sub.zwdk.org/qiq'
url_script='https://raw.githubusercontent.com/lmzxtek/qiqtools/refs/heads/main/src/qiqtools.sh'
url_update='https://raw.githubusercontent.com/lmzxtek/qiqtools/refs/heads/main/src/update_log.sh'

clear
echoR " >>> " $(echoY "脚本更新日志") $(echoR "<<<") 
echoB " - " $(echoT $url_update)
echoT "--------------------------------"
echoT " >>> 2024-3-12   v0.4.4" ""
echoT "   1.完成了站点部署菜单的各项功能。"
echoT "   2.添加了脚本更新日志的显示."
echoT "   3.修正了域名绑定时，重新加载出错的问题."
echoT "--------------------------------"
echoT " >>> 2024-3-12   v0.4.5" " "
echoT "   1.使用wget显示脚本日志。"
echoT "   2.用不同颜色显示日志，突出最新版本。"
echoT "--------------------------------"
echoT " >>> 2024-3-12   v0.4.6" " "
echoT "   1.添加容器管理菜单。"
echoT "   2.容器管理菜单检测Docker是否安装。"
echoT "--------------------------------"
echoT " >>> 2024-3-13   v0.4.7" " "
echoT "   1.添加容器GeminiProChat。"
echoT "   2.添加容器AKTools金融数据接口。"
echoT "   3.把src目录下面的sh脚本文件移动到了子目录。"
echoT "--------------------------------"
echoT " >>> 2024-3-14   v0.4.8" " "
echoT "   1.添加颜色显示说明。"
echoT "   2.添加前景色、背景色、字体全局变量。"
echoT "   3.将更新日志中的NEW字体更改为蓝色闪烁。"
echoT "   4.DD系统选择时显示默认的登录密码。"
echoT "--------------------------------"
echoT " >>> 2024-3-17   v0.4.9" " "
echoT "   1.添加Dash.部署。"
echoT "   2.修改DD菜单实现方式。"
echoT "--------------------------------"
echoT " >>> 2024-3-19   v0.5.0" " "
echoT "   1.添加WatchTower容器部署，随时更新容器镜像。"
echoT "   2.添加WireGuard Panel容器部署。"
echoT "   3.添加XBorad部署。"
echoT "   4.添加LotusBoard部署。"
echoT "   5.添加AKJupyter-Lab部署。"
echoT "   6.添加Jupyter-Lab部署。"
echoT "--------------------------------"
echoT " >>> 2024-3-23   v0.5.1" " "
echoT "   1.添加腾讯、清华、中科院源更换。"
echoT "   2.添加Warp(@p3terx)、Warp-go。"
echoT "   3.查询系统信息时，重新调用信息获取函数。"
echoT "   4.系统设置中添加系统信息入口。"
echoT "   5.添加DeepLX接口服务(包括Docker部署)。"
echoT "   6.增加卸载nginx功能。"
echoT "   7.设置IPv6域名解析的时候先进行备份。"
echoT "--------------------------------"
echoT " >>> 2024-3-26   v0.5.2" " "
echoT "   1.添加KASM平台的部署。"
echoT "   2.添加Neko平台的部署。"
echoT "   3.添加Neko-Rooms平台的部署。"
echoT "   4.添加Tor-Browser平台的部署。"
echoT "   5.添加Online Browser安装程序。"
echoT "   6.添加LinuxServer(firefox|Chromium)容器部署。"
echoT "--------------------------------"
echoT " >>> 2024-4-1   v0.5.3" " "
echoT "   1.将站点部署菜单中的非Docker部署移动到其他工具菜单。"
echoT "   2.添加主菜单项：IP检测优选。"
echoT "   3.添加Linux系统桌面GUI安装。"
echoT "   4.添加腾讯WebOS的安装。"
echoT "--------------------------------"
echoT " >>> 2024-4-7   v0.5.4" " "
echoT "   1.增加supervisor,fail2ban的安装。"
echoT "--------------------------------"
echoT " >>> 2024-4-26   v0.5.5" " "
echoT "   1.增加服务器管理工具Puter部署。"
echoT "   2.增加Windows版本的不同语言DD选项。"
echoT "   3.增加41合1DD脚本。"
echoT "-------------------------------"
echoT "   1.增加谷歌浏览器Chrome的安装。"
echoT " >>> 2024-5-25   v0.5.6" " "
echoT "   1.修改Alpine中BBrV3的安装。"
echoT "   2.增加爱影CMS内容管理系统的部署。"
echoT "   3.添加PostgreSQL数据库的安装，以及使用说明。"
echoT "--------------------------------"
echoT " >>> 2024-6-20   v0.5.7" " "
echoT "   2.增加pip的安装。"
echoT "   3.修改Caddy搭建网站时本地IP的默认值。"
echoT "   4.增加pure-ftp的常用工具安装。"
echoT "   5.增加Jupyter-lab非Docker部署。"
echoT "   6.增加Conda-forge的安装。"
echoT "--------------------------------"
echoT " >>> 2024-7-04   v0.5.8" " "
echoT "   1.让1Panel安装前不再先安装Docker。"
echoT "   2.更新Kejilion脚本代码。"
echoT "   3.添加Docker版的RDesktop部署。"
echoT "   4.修复系统更新源不链接不完整的Bug。"
echoT "--------------------------------"
echoT " >>> 2024-7-28   v0.5.9" ""
echoT "   1.修改1Panel安装支持。"
echoT "   2.添加脚本更新系统源镜像。"
echoT "   3.修改DD系统菜单。"
echoT "   4.增加ArchLinux系统的DD。"
echoT "   5.增加编译安装TA-Lib。"
echoT "--------------------------------"
echoT " >>> 2024-8-24   v0.6.0" " "
echoT "   1.修改DD成Windows的语言为中文(有问题，切换回了英文)。"
echoT "   2.增加下载DD脚本的下载菜单。"
echoT "   3.主菜单增加IP检测选项。"
echoT "   4.常用工具中添加KijiLion脚本。"
echoT "   5.增加ClamAV安装。"
echoT "--------------------------------"
echoT " >>> 2024-8-28   v0.6.1" " "
echoT "   1.增加h-ui面板部署。"
echoT "   2.增加容器Talk With Gemini的部署。"
echoT "   3.修改主菜单右侧图标。"
echoT "   4.添加GB5服务器测试脚本。"
echoT "   5.删除DD系统右侧的符号。"
echoT "--------------------------------"
echoT " >>> 2024-9-12   v0.6.2" " "
echoT "   1.更新KejiLion脚本命令。"
echoT "   2.添加Photopea的容器部署。"
echoT "   3.DD成win2022采用reinstall.sh脚本。"
echoT "   4.增加IP管理工具的安装。"
echoT "--------------------------------"
echoT " >>> 2024-10-04   v0.6.3" " "
echoT "   1.增加Sublink订阅管理部署(bin+docker)。"
echoT "   2.增加Lucky转发的部署(bin(v2.11.2)+docker)。"
echoT "   3.增加Docker-win/Docker-mac部署。"
echoT "   4.增加DataEase命令部署。"
echoT "   5.系统设置增加SSH转发功能开启。"
echoT "   6.添加容器网络1panel-v4v6。"
echoT "   7.Set Aliyun(pip)。"
echoT "   8.恢复Kejilion脚本大陆安装链接。"
echoT "   9.增加JumpServer堡垒机命令部署。"
echoT "--------------------------------"
echoT " >>> 2025-01-01   v0.6.4" " "
echoT "   1.增加Sky-Box工具箱。"
echoT "   2.添加Docker-Wechat部署。"
echoT "   3.添加IPTV部署。"
echoT "   4.增加DD选项 WinServer2025, 并去除2012。"
echoT "   5.修改安装所有软件选项为常用的工具：btop,failban,supervisor..."
echoT "--------------------------------"
echoT " >>> 2025-01-24   v0.6.5" " "
echoT "   1.脚本执行时请求IP"
echoT "   2.增加天气显示"
echoT "   3.增加pdf2zh(Docker)。"
echoT "   4.增加Akile Monitor脚本"
echoT "   5.新增iptv(doubebly)部署"
echoT "--------------------------------"
echoT " >>> 2025-03-03   v0.6.6" " "
echoT "   1.增加Julia(Linux)安装。"
echoT "   2.增加docker-compose-gpt_aca.yml。"
echoT "   3.一点科技Docker,Nginx,nezha(v1)安装。"
echoT "   4.将托管平台更换为GitCode"
echoT "--------------------------------"
echoT " >>> 2025-03-06   v0.7.0" " "
echoT "   1.脚本链接url使用变量"
echoT "   2.脚本更新添加链接地址"
echoT "   3.检测qiq命令是否设置"
echoT "   4.增加 pip install gunicorn ..."
echoT "   5.更换仓库为github平台."
echoT "--------------------------------"
echoR " >>> 2025-03-07   v0.7.1" " $VLATEST"
echoY "   1.更改脚本主菜单头"
echoT "--------------------------------"
echoR "" $(echoY "url") $(echoR ": $url_redir") 
echoR "" $(echoY "url") $(echoR ": $url_script") 